# Generated by Django 6.0.1 on 2026-01-31 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_color_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_image_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CardRarity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_rarity_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CardSubtype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_subtype_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_type_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('set_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('mana_cost', models.CharField(max_length=200)),
                ('cmc', models.IntegerField()),
                ('type_line', models.CharField(max_length=200)),
                ('oracle_text', models.TextField()),
                ('power', models.IntegerField()),
                ('toughness', models.IntegerField()),
                ('colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cardcolor')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cardimage')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cardrarity')),
                ('subtypes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cardsubtype')),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cardtype')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.set')),
            ],
        ),
    ]
