# Generated by Django 6.0.1 on 2026-01-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_card_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='card_images/'),
        ),
    ]
