services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: py_mtg_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mtg_db}
      POSTGRES_USER: ${POSTGRES_USER:-mtg_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mtg_pass}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      # Se quiser acessar/editar scripts sem rebuild, pode habilitar também:
      # - ./initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pg_data: